/* ============================================================================
   ZAVARI CONCEPTS — Demo tenant data
   Fictional company "Harbor" — the onboarding platform for B2B software.
   ONE strategy world, threaded through every screen. The spine scenario is
   the Opportunity: several large accounts independently started exporting
   onboarding data into outside tools — validated demand for Harbor's next
   product. Command Layer teases a Risk and a Scale item alongside it.

   Source taxonomy (matches the landing legend + accessibility tokens):
     kind 'owned'     → Zavari's tools      (navy dot)
     kind 'market'    → Market intelligence (azure dot)
     kind 'connected' → Your connected stack(gray dot)
   ============================================================================ */

window.ZV = (function () {

  const tenant = {
    name: 'Harbor',
    descriptor: 'Onboarding platform for B2B software',
    stage: 'Series B · 184 people',
    user: { name: 'Maya Okonkwo', role: 'VP Product' },
    lastSeen: 'Tuesday, 4:12pm',
  };

  const northStar = {
    label: 'WEEKLY ACTIVATED ACCOUNTS',
    value: '1,940',
    trend: '+6.2%',
    sub: 'Accounts reaching first value within 14 days',
  };

  // Strategic objectives (annual)
  const objectives = [
    {
      id: 'OBJ-1', code: 'O1', name: 'Win the mid-market',
      detail: 'Land and expand in 50–500 seat accounts.',
      owner: 'Priya R.', state: 'coherent',
      krs: [
        { kr: 'Mid-market ARR', now: '$8.4M', target: '$14M', pct: 60 },
        { kr: 'Logos 50–500 seats', now: '112', target: '180', pct: 62 },
      ],
    },
    {
      id: 'OBJ-2', code: 'O2', name: 'Make onboarding self-guided',
      detail: 'Cut time-to-first-value without adding support headcount.',
      owner: 'Maya O.', state: 'coherent',
      krs: [
        { kr: 'Activated within 14 days', now: '28%', target: '55%', pct: 51 },
        { kr: 'Support-touched setups', now: '71%', target: '40%', pct: 44 },
      ],
    },
    {
      id: 'OBJ-3', code: 'O3', name: 'Become the system of record',
      detail: 'Own the canonical onboarding record across the lifecycle.',
      owner: 'Dani L.', state: 'coherent',
      krs: [
        { kr: 'Accounts with 2+ workflows', now: '34%', target: '60%', pct: 57 },
        { kr: 'Template installs', now: '4.1k', target: '9k', pct: 46 },
      ],
    },
  ];

  // Active bets / initiatives. Coherence is read as insight, calmly — the story
  // is mostly bets holding together, with one that has come loose (an
  // opportunity to realign, never an alarm). The E opportunity is the lead bet.
  const bets = [
    {
      id: 'B1', name: 'Native data export & reporting', tag: 'Customer-pulled',
      ladder: 'OBJ-3', laddersTo: 'Become the system of record',
      state: 'coherent', roi: 88, effort: 'M', quarter: 'Next', confidence: 'high',
      lead: true,
      note: 'The behavior several accounts already improvised — brought inside the product. Extends the canonical record.',
    },
    {
      id: 'B2', name: 'Onboarding Copilot', tag: 'AI-guided setup',
      ladder: 'OBJ-2', laddersTo: 'Make onboarding self-guided',
      state: 'coherent', roi: 92, effort: 'L', quarter: 'Q3', confidence: 'high',
      note: 'Guides admins through setup; removes the top time-to-value blocker.',
    },
    {
      id: 'B3', name: 'Template Marketplace', tag: 'Owned surface area',
      ladder: 'OBJ-3', laddersTo: 'Become the system of record',
      state: 'coherent', roi: 74, effort: 'M', quarter: 'Q3', confidence: 'medium',
      note: 'Pre-built onboarding flows; deepens the canonical record.',
    },
    {
      id: 'B4', name: 'Enterprise sign-on & provisioning', tag: 'Table-stakes up-market',
      ladder: 'OBJ-1', laddersTo: 'Win the mid-market',
      state: 'coherent', roi: 68, effort: 'M', quarter: 'Q3', confidence: 'high',
      note: 'Unblocks security review in larger deals.',
    },
    {
      id: 'B5', name: 'Salesforce two-way sync', tag: 'Expansion motion',
      ladder: 'OBJ-1', laddersTo: 'Win the mid-market',
      state: 'coherent', roi: 63, effort: 'M', quarter: 'Q4', confidence: 'medium',
      note: 'Surfaces onboarding health to revenue teams.',
    },
    {
      id: 'B6', name: 'Mobile approver app', tag: 'Net-new surface',
      ladder: null, laddersTo: null,
      state: 'drifting', roi: 31, effort: 'M', quarter: 'Q4', confidence: 'low',
      note: 'No active objective claims it right now. Popular in a few accounts — worth a deliberate keep-or-cut.',
    },
  ];

  // The marquee proactive output — the Opportunity (E), in full.
  const brief = {
    id: 'SOB-118',
    kicker: 'STRATEGIC OPPORTUNITY BRIEF · GENERATED BY ZAVARI',
    generated: 'Generated proactively · Jul 6',
    title: 'Your customers are pointing at your next product.',
    standfirst:
      'Several of your largest accounts independently started exporting onboarding data into outside tools this quarter — reaching for a capability that is a natural next step from what Harbor already does. No feature request, no prompting; the pattern is accelerating. It reads as demand you can see before you have built anything.',
    coherence: { state: 'coherent', label: 'On-strategy', detail: 'Extends what customers already value' },
    recommendation:
      'Make native data export & reporting your next bet. Bring the behavior these accounts already improvised inside the product — and move before the market names the category.',
    projected: { value: '3.4×', unit: '', label: 'EXPANSION RATE OF ACCOUNTS ALREADY DOING THIS' },
    findings: [
      {
        n: 1, confidence: 'high',
        claim: 'The same new behavior, across several accounts — and accelerating.',
        detail: 'Six of your largest accounts independently began exporting onboarding data into outside analysis tools this quarter. None asked for it; each reached for the same missing step on their own, and the volume is climbing month over month.',
        sources: [
          { source: 'Zavari Research', kind: 'owned' },
          { source: 'Amplitude', kind: 'connected', count: 1240 },
          { source: 'Support', kind: 'connected', count: 46 },
        ],
      },
      {
        n: 2, confidence: 'high', coherent: true,
        claim: 'Validated demand — before you have built a thing.',
        detail: 'This is not a request you can discount. It is customers voting with behavior: the need is real, present, and already costing them a workaround. Zavari reads it as extending the core, not stretching away from it.',
        sources: [
          { source: 'Zavari Research', kind: 'owned' },
        ],
      },
      {
        n: 3, confidence: 'medium',
        claim: 'The market is only just forming here.',
        detail: 'No competitor has planted a flag on this yet. Move now and you define the category rather than chase it later.',
        sources: [
          { source: 'Market Intelligence', kind: 'market' },
        ],
      },
    ],
    // positive knock-on (was "second-order") — an upside, not a warning
    knockOn: {
      label: 'Knock-on effect',
      claim: 'The accounts already doing this are your fastest-expanding ones.',
      detail: 'Leading here deepens your best relationships — it doesn\u2019t just open a new market. The move compounds the advantage you already have.',
      sources: [
        { source: 'Zavari Strategy', kind: 'owned' },
        { source: 'Expansion data', kind: 'connected' },
      ],
    },
  };

  // Things Zavari surfaced since last login (Command Layer) — labeled by
  // approach: Opportunity (lead) · Risk · Scale. Each is a concrete observation.
  const surfaced = [
    {
      id: 's1', approach: 'Opportunity', tone: 'opportunity',
      headline: 'Six of your largest accounts independently started exporting onboarding data into outside tools.',
      meta: 'A natural next step from what Harbor already does — validated demand, no feature request. The pattern is accelerating.',
      confidence: 'high',
      sources: [
        { source: 'Zavari Research', kind: 'owned' },
        { source: 'Amplitude', kind: 'connected' },
        { source: 'Support', kind: 'connected' },
      ],
      to: 'brief', cta: 'Open the opportunity brief',
    },
    {
      id: 's2', approach: 'Risk', tone: 'risk',
      headline: 'A top account\u2019s weekly usage is down 22% — while its health score still reads green.',
      meta: 'It\u2019s tracing the curve that preceded last quarter\u2019s churn. The signal is weeks ahead of the dashboard — a conversation now, not a renewal later.',
      confidence: 'medium',
      sources: [
        { source: 'Amplitude', kind: 'connected' },
        { source: 'Support', kind: 'connected' },
      ],
      to: 'research', cta: 'See the signal',
    },
    {
      id: 's3', approach: 'Scale', tone: 'scale',
      headline: 'A capability you under-tell is quietly driving expansion.',
      meta: 'Your guided data-import flow retains better than anything else you ship — but it\u2019s under-told in your story and under-funded on the roadmap. Lean in and it compounds.',
      confidence: 'high',
      sources: [
        { source: 'Expansion data', kind: 'connected' },
        { source: 'Zavari Research', kind: 'owned' },
      ],
      to: 'coherence', cta: 'See where it fits',
    },
  ];

  // Source roster — Zavari's tools · market intelligence · your connected stack
  const sources = {
    owned: ['Zavari Strategy', 'Zavari Planning', 'Zavari Research', 'Zavari Product metrics'],
    market: ['Market Intelligence'],
    connected: ['Amplitude', 'Salesforce', 'Jira', 'Support', 'Notion'],
  };

  // Decision Record — the auditable chain behind the Opportunity recommendation
  const decision = {
    title: 'Make native data export & reporting Harbor\u2019s next bet',
    status: 'Committed', owner: 'Maya O.', date: 'Jul 6',
    chain: [
      { kind: 'North star', body: 'Weekly Activated Accounts', meta: 'The metric everything ladders to', src: [] },
      { kind: 'Objective', body: 'Become the system of record (O3)', meta: 'Own the canonical onboarding record across the lifecycle', src: ['Zavari Strategy'] },
      { kind: 'Insight', body: 'Six of your largest accounts independently started exporting onboarding data into outside tools — demand for a step Harbor doesn\u2019t cover yet.', meta: 'No feature request; customers voting with behavior', src: ['Zavari Research', 'Amplitude', 'Support'] },
      { kind: 'Decision', body: 'Scope native data export & reporting as the next bet; move before the market names the category.', meta: 'Extends the core — deepens the system-of-record objective', src: ['Zavari Strategy', 'Zavari Planning'] },
      { kind: 'Initiative', body: 'Native data export & reporting — discovery', meta: 'Planning · next quarter · owner Maya O.', src: ['Zavari Planning'] },
      { kind: 'Delivery', body: 'HAR-512 · Export & reporting discovery epic', meta: 'Jira · carries its reasoning forward', src: ['Jira'], byo: true },
    ],
  };

  // Research insights (qual) + survey-quant — aligned to the export opportunity
  const research = {
    insights: [
      { id: 'R1', theme: 'Data export', quote: 'Every Monday I export the whole onboarding log into a spreadsheet just to build the report my execs actually want.', who: 'Ops lead · 240-seat account', strength: 9, feeds: 'B1', feedsName: 'Native data export & reporting' },
      { id: 'R2', theme: 'Reporting gap', quote: 'The data is all in Harbor. I just can\u2019t get it out in a shape anyone upstairs will read.', who: 'Admin · 180-seat account', strength: 8, feeds: 'B1', feedsName: 'Native data export & reporting' },
      { id: 'R3', theme: 'Mobile sign-off', quote: 'I approve onboarding steps from my phone, but I have to wait until I\u2019m at a laptop.', who: 'Director · 90-seat account', strength: 4, feeds: null, feedsName: null },
    ],
    survey: {
      q: 'Where does Harbor\u2019s data leave the product today?', n: 312,
      bars: [
        { label: 'Exported to a spreadsheet', pct: 44 },
        { label: 'Rebuilt in a BI tool', pct: 27 },
        { label: 'Copied into a deck', pct: 18 },
        { label: 'Stays in Harbor', pct: 8 },
        { label: 'Other', pct: 3 },
      ],
    },
  };

  // Product metrics — thin capture (onboarding funnel)
  const funnel = [
    { step: 'Signed up', pct: 100 },
    { step: 'Invited team', pct: 71 },
    { step: 'Imported data', pct: 49 },
    { step: 'First customer onboarded', pct: 34 },
    { step: 'Activated (within 14 days)', pct: 28 },
  ];

  // Ecosystem model for the platform / map screens.
  // Zavari's tools · market intelligence · your connected stack. Names spelled
  // out. No "ships first" markers, no named bridges.
  const ecosystem = {
    intelligence: [
      { id: 'cmd', name: 'Strategic Command Layer' },
      { id: 'briefs', name: 'Opportunity Briefs' },
      { id: 'coh', name: 'Coherence Map' },
      { id: 'rec', name: 'Decision Record' },
    ],
    owned: [
      { id: 'strategy', name: 'Strategy / OKR', mono: 'St', note: 'North star & objectives' },
      { id: 'planning', name: 'Planning / Roadmap', mono: 'Pl', note: 'Initiatives & specs' },
      { id: 'research', name: 'Research', mono: 'Re', note: 'Qualitative + survey' },
      { id: 'metrics', name: 'Product metrics', mono: 'Pm', note: 'Lightweight metric capture' },
      { id: 'documents', name: 'Documents', mono: 'Do', note: 'Lightweight strategy docs' },
    ],
    market: [
      { id: 'market', name: 'Market Intelligence', mono: 'Mi', note: 'Synthesized from the open web, or your own sources' },
    ],
    connected: [
      { id: 'analytics', name: 'Analytics', mono: 'Am', note: 'Amplitude' },
      { id: 'delivery', name: 'Delivery', mono: 'Ji', note: 'Jira / Linear' },
      { id: 'docs', name: 'Documents', mono: 'No', note: 'Confluence / Notion' },
    ],
  };

  return {
    tenant, northStar, objectives, bets, brief, surfaced, sources,
    decision, research, funnel, ecosystem,
  };
})();
